# Generated by Django 4.0.6 on 2022-07-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_age_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Участник', 'member'), ('Модератор', 'moderator'), ('Админ', 'admin')], default='member', max_length=20),
        ),
    ]
