# Generated by Django 4.0.6 on 2022-07-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Участник'), ('moderator', 'Модератор'), ('admin', 'Админ')], default='member', max_length=20),
        ),
    ]
