# Generated by Django 4.0.6 on 2022-07-11 17:35

from django.db import migrations, models
import share.api.custom_validators
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True, validators=[users.models.age_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, validators=[share.api.custom_validators.rambler_ban_validator]),
        ),
    ]
