# Generated by Django 4.0.6 on 2022-07-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
        ('selections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='items',
            field=models.ManyToManyField(blank=True, to='ads.ad'),
        ),
    ]
